name: ci

on: [push, pull_request]

jobs:
  test:
    name: Build on ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        go: ['1.17']
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0

    - name: Download dependencies
      run: go mod download

    - name: Cache modules
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}

    - name: Build
      run: go build

    - name: Test
      run: go test ./...

    - name: Lint
      run: go vet ./...
